### ISSUE TITLE
Warning on Kobra 2 Neo and question

### ISSUE THREAD

**Issue by jonathan-realman** [1coderookie/Klipper4Kobra2series#8]
Hello, first of all thanks a ton for all the work you put in I am beyond happy to see that someone has taken an interest in the Kobra 2 Neo. I am very new to Klipper having only played around with marlin 2 years ago but one of the calls in the cfg seems to be depricated, if I happen to learn how to replace this my self I will push a commit. And secondly, is the auto Z offset available as a macro or similar.

![image](https://github.com/1coderookie/Klipper4Kobra2series/assets/43113264/0e4569d3-2503-4fe2-bbd2-060fd1ccad21)

**Comment by 1coderookie** [comment]
Thanks, I just updated the file.  
The auto z-offset feature can probably be implemented with a plugin, I think I read sth about it somewhere. But even then, just like with the stock fw, you usually still have to manually finetune your z-offset, as that auto z-offset function is only an approach to a somewhat okay-ish value. So just set it regularly and that's it - the z-offset really works with Klipper.
